### ISSUE TITLE
Support URL environment variable

### ISSUE THREAD

**Issue by c410-f3r** [rust-db/refinery#102]
Is it possible to add a database URL environment variable as a fallback if the config file is missing?

**Comment by jxs** [comment]
Hi, what would the idea be? at the moment you can set the [`db_host` and `db_port` via `Config`](https://docs.rs/refinery/0.3.0/refinery/config/struct.Config.html#method.set_db_host)

**Comment by c410-f3r** [comment]
It is easier to set a variable for dev, test or qa instead of having 3 different files that are a bit harder to maintain.
Another thing that may annoy embedded deploying is the additional dependencies for someone that is using a different runtime like `async-std`.

**Comment by jxs** [comment]
> It is easier to set a variable for dev, test or qa instead of having 3 different files that are a bit harder to maintain.

yeah, I can understand that, i was asking what the purposed API would be

> Another thing that may annoy embedded deploying is the additional dependencies for someone that is using a different runtime like async-std.

how so? both of the async drivers are coupled to `tokio`

**Comment by c410-f3r** [comment]
> yeah, I can understand that, i was asking what the purposed API would be

I see now. Well, something like: Look for config file, if not, look for DATABASE_URL, if not, then fail. 
Not sure if this approach is realistic within the current architecture. Maybe, maybe, maybe I will provide a PR to demonstrate this strategy with enough free-time. 

> how so? both of the async drivers are coupled to tokio

Although not very idiomatic in some cases, I **personally** prefer to send an ephemeral compiled CLI binary along side the application as part of a deploying script. This is just me and it isn't related to this PR

**Comment by jxs** [comment]
>I see now. Well, something like: Look for config file, if not, look for DATABASE_URL, if not, then fail.
Not sure if this approach is realistic within the current architecture. Maybe, with enough free-time, I will provide a PR to demonstrate this strategy.

what if there was a method on Config to instantiate from environment variables?

**Comment by c410-f3r** [comment]
Looks good! A `from_env_var` doesn't seem much different from `from_file_location`.

**Comment by jxs** [comment]
ok great! do you want to give it a go then?

**Comment by c410-f3r** [comment]
@jxs #103
