### ISSUE TITLE
Feature Request (or Question?): Support deadpool / tokio postgres

### ISSUE THREAD

**Issue by eiswind** [rust-db/refinery#105]
I would appreciate some help with my poor understanding of the type system...

```
let mut client = db_pool.get().await?.deref_mut().deref_mut();
    let report = embedded::migrations::runner()
        .run_async(&mut client)
        .await?;
```
using deadpool with tokio-postgres and I get the following compile error (that I do not understand, really :)
```
 the trait `refinery::AsyncMigrate` is not implemented for `&mut tokio_postgres::client::Client`
```

**Comment by jxs** [comment]
hi, it's `run_async(client)`:
```rust
    let mut obj = pool.get().await?;
    let client = obj.deref_mut().deref_mut();
    let _report = embedded::migrations::runner()
        .run_async(client)
        .await?
```

**Comment by eiswind** [comment]
Thx a lot, that helped!

**Comment by mpiorowski** [comment]
@jxs You should add this to the doc really :) Now most of the pg connection are done via pooling.

**Comment by jxs** [comment]
hi @mpiorowski makes sense yeah thanks,wanna go ahead and submit a PR with it?

**Comment by mpiorowski** [comment]
> hi @mpiorowski makes sense yeah thanks,wanna go ahead and submit a PR with it?

@jxs done :)
