### ISSUE TITLE
Feature Request: Renaming migrations table

### ISSUE THREAD

**Issue by ksten-ab** [rust-db/refinery#109]
I'd like for it to be possible to change the table name (and possibly the schema name) of the migrations table.

This could potentially be accomplished by passing a config argument to the `runner` api; or alternatively by allowing optional arguments in the "include" macros.

**Comment by jxs** [comment]
Hi, can you elaborate on what use cases/advantages would that bring?

**Comment by ksten-ab** [comment]
@jxs - Yeah!  I think this is the primary use:

- If you want to run multiple projects – each using refinery to manage migrations – out of the same database, their migration table names need to be different.
   > An argument I've seen against this, is that you can't trust the migrations from different project not to conflict.  I feel that's a weak argument, esp. because someone who is going out of their way to change the migration name (e.g., by specifying extra arguments) is more likely to carefully manage the namespace of their tables.
   > **In the spirit of Rust**, while Rust provides a "safer" happy path, it also doesn't prevent you from reaching for more powerful tools when they are necessary.

A secondary use might be that an open source project wants to specify the name of a the migrations table for the project, so that it is clear when someone is exploring/inspecting the database where/what/who the table was generated by.

**Comment by jxs** [comment]
ok yeah makes sense, want to give it a go?

**Comment by johnsom** [comment]
I would also like to be able to specify the schema for the history file.

**Comment by jxs** [comment]
addressed with https://github.com/rust-db/refinery/pull/207
