### ISSUE TITLE
Provide example of how to use SQLx with SQLite

### ISSUE THREAD

**Issue by robinhundt** [rust-db/refinery#110]
Hey there,
the `README` currently states that

> If you are using a driver that is not yet supported, namely SQLx you can run migrations providing a Config instead of the connection type, as Config impl's Migrate. You will still need to provide the postgres/mysql/rusqlite driver as a feature for Runner::run and tokio-postgres/mysql_async for Runner::run_async.

Having never used this crate i can't quite make sense of that passage. I see that you could provide a `Config` to the `Runner::run` method. But i'm not sure how to initialize it, considering i want to use SQLx with SQLite. And how can i pass the the rusqlite driver along with the `Config`?

An example, or some pointers, of how to use refinery alongside SQLx and SQLite would be greatly appreciated.

**Comment by jxs** [comment]
Hi, does [this test](https://github.com/rust-db/refinery/blob/master/refinery/tests/rusqlite.rs#L532) example help?

**Comment by robinhundt** [comment]
Yes, that test helped me. Got it running.
Thank you very much :blush:
