### ISSUE TITLE
Feature request: Get latest known migration / all known migrations

### ISSUE THREAD

**Issue by jakajancar** [rust-db/refinery#117]
`Runner` struct has a `migrations` property, but it is not public. Would be nice to expose that, and maybe even some convenience methods:

  - `get_last_known_migration()`
  - `are_all_migrations_applied()`

**Comment by jxs** [comment]
Hi, `Runner` has [`get_applied_migrations`](https://docs.rs/refinery/0.3.0/refinery/struct.Runner.html#method.get_applied_migrations) and [`get_last_applied_migration`](https://docs.rs/refinery/0.3.0/refinery/struct.Runner.html#method.get_last_applied_migration), don't those work for your case?

**Comment by jakajancar** [comment]
I would like to know the unapplied ones, though.

For example, how do I find out if the database if up-to-date? I could scan the migrations directory myself, but that seems duplicating the functionality.

**Comment by jxs** [comment]
i see, i am open to adding a public `migrations` getter to the `Runner` struct, if you want to submit a PR

**Comment by jakajancar** [comment]
See [here](https://github.com/rust-db/refinery/pull/120).

Tests don't pass for me on master btw:

```
---- config::tests::builds_db_env_var stdout ----
thread 'config::tests::builds_db_env_var' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigError("Couldn\'t parse the string \'this_is_not_a_url\' as a URL"), report: None }', refinery_core/src/config.rs:350:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    config::tests::builds_db_env_var
```
