### ISSUE TITLE
Feature request: Add some logging or a callback

### ISSUE THREAD

**Issue by jakajancar** [rust-db/refinery#118]
I'd like to log "Applying X" before each migration starts, to be able to know what's going on. As far as I know, currently, you only know once everything has been done.

**Comment by jxs** [comment]
Hi, that is not true: check [here](https://github.com/rust-db/refinery/blob/master/refinery_core/src/traits/sync.rs#L34) and [here](https://github.com/rust-db/refinery/blob/master/refinery_core/src/traits/async.rs#L38)

**Comment by jakajancar** [comment]
Ah, great, thanks!
