### ISSUE TITLE
Run migration in seleceted schema in postgresql

### ISSUE THREAD

**Issue by dancespiele** [rust-db/refinery#123]
How can I run migrations in a selected schema postgresql? Always it runs the migrations in the public schema and I don't see how can I choose it in the documentation.

Update:
Even if I choose schema with barrel, doesn't work

**Comment by jxs** [comment]
Hi, yeah at the moment it's not possible, ideally this would be solved by #109 right?

**Comment by dancespiele** [comment]
I realized that with barrel reads all the schemas finding the migration table in each one. You can run the migration in another schemas but if one schema has the migration until v3 for example you need to call the migration of the another schema v4, for me that behaviour is ok however for multiple teams that works in microservers and each one use a schema could be an issue. Another thing that I want to mention is that [barrel](https://github.com/rust-db/barrel) looks unmaintained even there are a PR and issues without answers, I think the project is great and worth (I'm using that in my projects), also there is not something like this in rust, at least what I know. Is there intention to continue maintain it?

**Comment by jxs** [comment]
addressed with https://github.com/rust-db/refinery/pull/207
