### ISSUE TITLE
Compiler crashes on windows 10

### ISSUE THREAD

**Issue by yamashi** [rust-db/refinery#140]
Hello,

Adding refinery 0.3.0 to Cargo.toml on windows 10 crashes rustc 1.47.0 (18bf6b4f0 2020-10-07).
I don't know if this is known and do not know how to report this kind of issue to rust-lang.

Edit: Problem still happens with 0.4.0

**Comment by yamashi** [comment]
I updated my toolchain to beta-x86_64-pc-windows-gnu and now the compiler does not crash but the linker outputs an error:
`D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 77144`

**Comment by jxs** [comment]
Hi, the windows builds are running: https://travis-ci.org/github/rust-db/refinery. That seems to be a compiler problem, I would suggest to open an issue in https://github.com/rust-lang/rust
