### ISSUE TITLE
Postgres feature does not implement Migrate for Client

### ISSUE THREAD

**Issue by cschmatzler** [rust-db/refinery#144]
Hi,

I am trying to make refinery migrations work with postgres, but I cannot figure out what is going wrong.

My `Cargo.toml` dependencies are as follows:
```
[dependencies]
barrel = { version = "0.6.5", features = ["pg"] }
postgres = "0.19.0"
refinery = { version = "0.4.0", features = ["postgres"] }
```

My `main.rs` is:
```
use postgres::{Client, NoTls};
use std::env;

mod migrations;

fn main() {
    let db_url = env::var("DB_URL").expect("DB_URL environment variable is missing.");
    let mut client = Client::connect(&db_url, NoTls).expect("Error connecting to database");

    migrations::runner().run(&mut client).expect("Error while running migrations.");
}
```

This does not compile with:
```
error[E0277]: the trait bound `Client: Migrate` is not satisfied
  --> migrations/src/main.rs:10:30
   |
10 |     migrations::runner().run(&mut client).expect("Error while running migrations.");
   |                              ^^^^^^^^^^^ the trait `Migrate` is not implemented for `Client`
```

From what I have seen, this usually happens when the `postgres` feature is not enabled, but I have double checked and also removed the `target` folder and refetched all dependencies.

Pinning the `postgres` crate to `0.18`, which is what is used in `refinery-core` does not fix this.

Maybe I am being super stupid, but any help would be greatly appreciates.

Cheers, stay safe and have a healthy start into the new year.

**Comment by jxs** [comment]
Hi,
yeah to use refinery `0.4.0` you have to use postgres `0.17` see [here](https://github.com/rust-db/refinery/blob/v0.4/refinery_core/Cargo.toml#L30).
If you want to use postgres `0.19` you can use refinery `master`.

**Comment by cschmatzler** [comment]
Looking at the dependencies in `master` might have not been my smartest movie. Sorry about that and thanks!

**Comment by erayerdin** [comment]
I'm coming here from google to inform that one needs to use `run_async` instead of `run` if they use `tokio-postgres`.
