### ISSUE TITLE
Feature request: abiliy to use both .sql and .rs migrations

### ISSUE THREAD

**Issue by Jackneill** [rust-db/refinery#154]
Example usage could be:
`src/store/migrations/mod.rs`:
```rust
use refinery::{
    embed_migrations,
    include_migration_mods,
};

embed_migrations!(".");
include_migration_mods!(".");

//or something like:
//hybrid_migrations!(".");
```
```bash
$ ls src/store/migrations
mod.rs
V1__init.rs
V2__update.sql
...
```

**Comment by ruseinov** [comment]
@jxs any idea how to approach this?

**Comment by jxs** [comment]
Hi, maybe we could have a `hybrid_migrations!` macro that calls the other two and merges the list returned by each, wdyt?

**Comment by omid** [comment]
I don't have deep knowledge of refinery, but...

Why do we need 3 different macros? I think one is enough.
We can crawl the directory, interpret files, based on extension do `#ident::migration()` or `include_str!(#path).to_string()`.

wdyt?

**Comment by omid** [comment]
OK, please check my proposal in the PR #170.
