### ISSUE TITLE
Support for AWS RDS Data API

### ISSUE THREAD

**Issue by rockstar** [rust-db/refinery#155]
I'm using the [AWS RDS Data API](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html) as my database backend. Essentially, it boils down to an HTTP interface where one `POST`s sql to `/ExecuteStatement` (or a variety of endpoints), and gets back data from the execution. The `rusoto_rds_data` crate makes this an api that boils down to a call to `RdsDataClient.execute_statement`; this seems like a relatively straightforward use for migrations, so I started doing:

    struct Connection {}
    impl Migrate for Connection {}

...and the error I get is 

    the trait bound `Connection: refinery_core::traits::r#async::AsyncQuery<Vec<Migration>>` is not satisfied
    the trait `refinery_core::traits::r#async::AsyncQuery<Vec<Migration>>` is not implemented for `Connection`

Unfortunately, I can't get to `AsyncQuery`, as it's not public. I looked at using `Config`, except `Config` assumes details about auth that don't apply well to the RDS Data API (it uses arns for the database and the secret arn). I'd be okay with implementing a trait that gave me postgres sql that I execute and return some result information, which seems to _kinda_ exist now, but just not in a way I _think_ I can consume. If I've missed something, I'd love to know that.

With some guidance, I'd even be interested in implementing this myself, if there is interest for it.

**Comment by jxs** [comment]
Hi, and thanks for the interest!
Honestly this seems like a niche case to support, but if `pub`ed `Query` and `AsyncQuery` ([they are already pub on `refinery_core`](https://github.com/rust-db/refinery/blob/main/refinery_core/src/traits/async.rs#L19)) and the other traits you could impl for your usecase right?

**Comment by rockstar** [comment]
Yeah, they're `pub` for the module, but the `refinery_core::traits` isn't `pub`, so I still can't get to it. If you just published the interfaces I would need to implement myself, I'd be happy to just keep the implementation local. I'm not sure if it's niche or just niche for now (the RDS Data API is new-ish, but I can see it being very helpful for lots of folks).

**Comment by jxs** [comment]
do you want submit a PR `pub`ing them?
