### ISSUE TITLE
refinery 0.4.0 incompatible with serde 1.x.x

### ISSUE THREAD

**Issue by jeffrey-afk** [rust-db/refinery#160]
From version 1.0.118 onwards `serde` a few modules got renamed. One is `export` that is used by the `runner.rs` in `refinery-core` version 0.4.0.

This issue seems to be resolved in `refinery-core` version 0.5.0.

Would it be possible to make a patch release 0.4.1 in which this is resolved? It should be a simple change in the import of the formatter.

`use serde::export::Formatter;`
in line 11 of `runner.rs` in `refinery-core` version 0.4.0 should be changed into 
`use std::fmt::Formatter;`

(First issue ever posted, apologies if it is unclear.)

**Comment by jxs** [comment]
see https://github.com/rust-db/refinery/issues/150
