### ISSUE TITLE
Migrations fails at checksum assertion

### ISSUE THREAD

**Issue by nikibor** [rust-db/refinery#161]
Same *.sql postgresql migration files passes on version 0.2.1 and fail with divergent error on 0.5.0. 
How to pass migrations, to pass checksum assertion?

Error with out set_abort_divergent(false) :
```
May 11 12:46:17.301  INFO tokio_postgres::connection: NOTICE: relation "refinery_schema_history" already exists, skipping    
thread 'main' panicked at 'can't apply DB migration Error { kind: DivergentVersion(Migration { state: Applied, name: "meetings", checksum: 16295495593068332098, version: 1, prefix: Versioned, sql: None, applied_on: Some(2020-10-15T13:59:27.297123706+00:00) }, Migration { state: Unapplied, name: "meetings", checksum: 2713139411990598374, version: 1, prefix: Versioned, sql: Some("my sql code"), applied_on: None }), report: None }', sandbox/db/src/main.rs:68:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Error with set_abort_divergent(false):
```
May 11 15:01:25.724  INFO tokio_postgres::connection: NOTICE: relation "refinery_schema_history" already exists, skipping    
May 11 15:01:25.728 ERROR refinery_core::traits: applied migration V1__meetings is different than filesystem one V1__meetings    
May 11 15:01:25.729 ERROR refinery_core::traits: applied migration V2__active_offers is different than filesystem one V2__active_offers    
May 11 15:01:25.729 ERROR refinery_core::traits: applied migration V3__transcom_hosts is different than filesystem one V3__transcom_hosts    
May 11 15:01:25.729 ERROR refinery_core::traits: applied migration V4__meetings_callid is different than filesystem one V4__meetings_callid    
May 11 15:01:25.729 ERROR refinery_core::traits: applied migration V5__transcom_language is different than filesystem one V5__transcom_language    
May 11 15:01:25.729  INFO refinery_core::traits: current version: 5    
May 11 15:01:25.729  INFO refinery_core::traits::r#async: no migrations to apply 
```   

Old Cargo.toml:

> refinery = {version = "0.2.1", features = ["tokio-postgres"]}
> refinery-macros = "0.2.0"

Old lib.rs:

> #[cfg(not(test))]
> pub mod embedded {
>     use refinery_macros::embed_migrations;
>     embed_migrations!("sandbox/db/migrations");
> }

Old main.rs:

> let client = conn.deref_mut().deref_mut();
>         let res = lib::embedded::migrations::runner()
>             .run_async(client)
>             .await;
>         if let Err(err) = res {
>             panic!(
>                 "can't apply DB migration {:?}",
>                 err
>             );
>         }
> 

New Cargo.toml:

> refinery = { version = "0.5.0", features = ["tokio-postgres"] }

New lib.rs:

> #[cfg(not(test))]
> pub mod embedded {
>     use refinery_macros::embed_migrations;
>     embed_migrations!("./migrations");
> }
>

**Comment by jxs** [comment]
Hi, version 0.2 used Rust's `DefaultHasher`, [we have since switched to the siphasher crate](https://github.com/rust-db/refinery/pull/63/files) on version 0.3. I don't know if Rust changed anything in the `DefaultHasher` implementation, [from the history of the file is hard to understand](https://github.com/rust-lang/rust/commits/master/library/core/src/hash/sip.rs)

**Comment by nikibor** [comment]
Thank you for direction of search. 
`checksum` field of migration struct is different in refinery-core 0.2 ver and 0.5, because of the selected hash function.
Almost out of mind. Same version, sql and name fields, but different sums and in check
