### ISSUE TITLE
Rename "refinery_schema_history" to something starting with __

### ISSUE THREAD

**Issue by omid** [rust-db/refinery#176]
To be compatible with diesel [print-schema command](https://diesel.rs/guides/schema-in-depth.html), I would suggest we can rename the migration table to something else which starts with __ (a double underscore).

**Comment by jxs** [comment]
hum, what is the advantage with this? Don't `diesel` and `refinery` kinda overlap? My issue with this is the same with [changing the type on the version column](https://github.com/rust-db/refinery/issues/83): a breaking change that envolves manually renaming a table. For this I would prefer we actually go for https://github.com/rust-db/refinery/issues/109 with the default being `refinery_schema_history`

**Comment by omid** [comment]
There is an overlap between `diesel_migrations` and `refinery`.
There are some overlaps between `refinery_cli` and `diesel_cli`.

`diesel cli` can generate the `schema.rs` file, which is kinda required if you want to use diesel.

And diesel will skip tables that starts with `__` in the schema.
