### ISSUE TITLE
CHANGELOG.md for version 0.6.0 lists wrong version of rusqlite update

### ISSUE THREAD

**Issue by UrsMetz** [rust-db/refinery#186]
The changelog currently says that with version 0.6.0 rusqlite was updated to 0.26 (in #159) but actually it was updated to 0.25.x (the constraint reads as `>= 0.23, < 0.26`cf. https://github.com/rust-db/refinery/blob/7ed3c85d8ac1129813daa683647c4529de1aadb1/refinery_core/Cargo.toml#L29).

**Comment by jxs** [comment]
Hi, thanks for noticing! Would you like to submit a PR updating the CHANGELOG?
