### ISSUE TITLE
Dependency Conflict with r2d2_sqlite

### ISSUE THREAD

**Issue by ALMaclaine** [rust-db/refinery#198]
I'm trying to use refinery with r2d2_sqlite but I get the following dependency conflict error.

I'm still relatively new to rust and investigated this issue for several hours before determining it seemed refinery was the limiting issue. If this is a problem with r2d2_sqlite please let me know:

```
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `rusqlite v0.23.0`
    ... which satisfies dependency `rusqlite = ">=0.23, <0.26"` of package `refinery-core v0.7.0`
    ... which satisfies dependency `refinery-core = "^0.7.0"` of package `refinery v0.7.0`
    ... which satisfies dependency `refinery = "^0.7.0"` of package `todo_app v0.1.0 (/Users/Diatta/CLionProjects/rust-react-todo-app)`
versions that meet the requirements `^0.18.0` are: 0.18.0
the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.23.0`
    ... which satisfies dependency `libsqlite3-sys = "^0.23.0"` of package `rusqlite v0.26.3`
    ... which satisfies dependency `rusqlite = "^0.26"` of package `r2d2_sqlite v0.19.0`
    ... which satisfies dependency `r2d2_sqlite = "^0.19.0"` of package `todo_app v0.1.0 (/Users/Diatta/CLionProjects/rust-react-todo-app)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='libsqlite3-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.
failed to select a version for `libsqlite3-sys` which could resolve this conflict
Process finished with exit code 101
```

**Comment by Pierstoval** [comment]
I just stumbled upon the same error.

It's because of two issues:

* `r2d2_sqlite` needs `rusqlite` with version `0.26` at least
* When you enable the any of the `rusqlite*` features on `refinery` in your `Cargo.toml`, and `refinery_core` needs `rusqlite` version `>= 0.23, < 0.26`, so they're incompatible.

A solution could be to use the latest development build of `refinery_core` at least, I'm looking for a workaround right now, will keep in touch if I find something (and if I don't, well, I won't 😛 )

**Comment by Pierstoval** [comment]
Well, I made compilation work by changing the `refinery` dependency with something like that:

```toml
[dependencies.refinery]
rev = "cfe9eb8439ec44a6da8cae41afb9007487ed0e08" # Current latest commit
git = "https://github.com/rust-db/refinery"
features = [ "rusqlite-bundled" ]
```

**Comment by jxs** [comment]
Hi, and thanks for your interest! I think we can remove that constraint, do any of you want to submit a PR :grin: ?

**Comment by ALMaclaine** [comment]
@jxs I think the code is fine, the current Cargo.toml for refinery-core has < 0.27, I believe the package needs to be published?

**Comment by Pierstoval** [comment]
@jxs Might want take a look at #200 😉

**Comment by jxs** [comment]
I am going to release a new version today.
Thanks! :)

**Comment by jxs** [comment]
done: https://github.com/rust-db/refinery/pull/201
