### ISSUE TITLE
Compatibility with mysql 22

### ISSUE THREAD

**Issue by Christoph-AK** [rust-db/refinery#204]
https://github.com/blackbeam/rust-mysql-simple was updated a few days ago to 22.0.0. 
This seems to be breaking the migrate implementation for PooledConn. 

 ```
let opts = Opts::from_url(&dbstring).unwrap();
let opts = OptsBuilder::from_opts(opts)
    .read_timeout(Some(std::time::Duration::from_secs(5 * 60)))
    .write_timeout(Some(std::time::Duration::from_secs(5 * 60)))
    .tcp_connect_timeout(Some(std::time::Duration::from_secs(5 * 60)))
    .tcp_keepalive_time_ms(Some(5 * 60 * 1000u32));

let pool = Pool::new(opts).unwrap();
let pool: Db = Arc::<Pool>::new(pool);

let mut conn = pool.get_conn().unwrap();

embedded::migrations::runner().run(&mut conn).unwrap();
```

throws 'Migrate not implemented for PooledConn' when on 
`refinery = { version = "0.8.1", features = ["mysql"] }` and `mysql = "22.0.0"`

**Comment by jxs** [comment]
Hi! Can you confirm https://github.com/rust-db/refinery/pull/202 addressed this? Will cut a new release if so :)

**Comment by Christoph-AK** [comment]
Hey there, works like a charm! Thanks @TobiasDeBruijn aswell!

**Comment by TobiasDeBruijn** [comment]
Awesome! Then I can remove another `patch` from my manifests. Thanks!
