### ISSUE TITLE
.sql migrations only allow a single statement

### ISSUE THREAD

**Issue by starsheriff** [rust-db/refinery#21]
Nice project, I tried to use it with one of my projects but stumbled across a limitation in the refinery_cli. It only allows a single statement in any `.sql` file. In my case I want to create multiple tables but it fails with the error

>Error: `error applying migration V2__demo`, `database error: ERROR: cannot insert multiple commands into a prepared statement`

`.sql` file:
```
create table roles (
    role varchar(32) PRIMARY Key,
);

create table powers (
    role_id SERIAL PRIMARY KEY,
);
```

**Comment by jxs** [comment]
Hi
I've submitted #22 which fixes it. 
I was planning on adding a new alpha version supporting [tokio-postgres](https://crates.io/crates/tokio-postgres) and [mysql_async](https://crates.io/crates/mysql_async) which also adds the trait updates on #20 tomorrow or so, would you mind installing from git till then? 
thanks

**Comment by starsheriff** [comment]
cool, thanks for the quick response. Installing from source is fine :+1:
