### ISSUE TITLE
Pass client from deadpool pool to Refinery - Migrate not implemented

### ISSUE THREAD

**Issue by alexhalford** [rust-db/refinery#231]
I am trying to use Refinery with a tokio-postgres client from a deadpool pool, like so:

```
async fn main() -> std::io::Result<()> {
     let config = crate::config::Config::from_env().unwrap();
     let pool = config.pg.create_pool(None, NoTls).unwrap();              // Returns a deadpool::managed::Pool<Manager>
     let migration_outcome = task::spawn_blocking(move || async {
         let mut client = pool.get().await.unwrap();
         embedded::migrations::runner().run(&mut client).unwrap();      // `deadpool::managed::Object<Manager>: Migrate` is not satisfied
     }).await?;
]
```
I guess I could try creating a non-pool client just for the migrations, but that feels a bit ugly. 

I would really appreciate some help. Thanks in advance!

**Comment by jxs** [comment]
Hi, and thanks for the interest!
Yeah `Migrate` isn't impl'ed for `deadpool::managed::Pool<Manager>` you need probably need to call [`Pool::get`](https://docs.rs/deadpool/0.9.5/deadpool/managed/struct.Pool.html#method.get) to get the underlying `tokio-postgres` connection

**Comment by alexhalford** [comment]
Thank you for the response. I assumed that was what I would get from `pool.get()`, but I will do some more digging

**Comment by jhelwig** [comment]
@alexhalford Looks like this comment might have the necessary incantation? https://github.com/rust-db/refinery/issues/105#issuecomment-638174424

**Comment by alexhalford** [comment]
I tried that, it didn't work, but thank you. I actually ended up using this:
```
let tokio_config = cfg.get_pg_config().unwrap();
```
Which gives you a tokio-postgres config from a deadpool config, which you can then call `.connect` on to instantiate a normal, non-pooled connection.

Thank you both for your help, I really appreciate the responsiveness, and refinery has been great so far.
