### ISSUE TITLE
Supporting, and using custom SQL databases.

### ISSUE THREAD

**Issue by michaelgrigoryan25** [rust-db/refinery#233]
Currently, Refinery does not support CockroachDB as a target SQL database for migrations. Whenever I try running the migrations with the connection string that points to my CockroachDB instance, I get an error related to the `pg_advisory_lock` function, which is exclusive to PostgreSQL. CockroachDB might never support this functionality, which is discussed in https://github.com/cockroachdb/cockroach/issues/13546. Now, my question is would it be possible to implement some trait that would allow us to use a custom connector to an SQL database to run our migrations, instead of the ones provided by the crate's features? 

If you would consider adding this feature, just let me know how I can help. I would be happy to contribute.

**Comment by jxs** [comment]
Hi!
`refinery` uses [`postgres`](url)  as the PostgreSQL driver, afaik it [supports Cockroach db ](https://github.com/sfackler/rust-postgres/issues/171) so I would suggest discussing there?

Thanks :)

**Comment by michaelgrigoryan25** [comment]
Thanks for getting back to my issue. Now it works fine, and I think the issue was that my driver versions did not match. Also, is the project in maintenance mode?

**Comment by jxs** [comment]
>Thanks for getting back to my issue. Now it works fine, and I think the issue was that my driver versions did not match. Also, is the project in maintenance mode? 

No worries, and no it's not in maintenance mode :)

>And finally, is using barrel still supported? I cannot get it to work with refinery, since the compiler is saying that some components (which are in the documentation) are missing.

we use `barrel` on the `refinery` tests, so yeah it's still supported. Can you open another issue with a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)?

Thanks

**Comment by michaelgrigoryan25** [comment]
> No worries, and no it's not in maintenance mode :)

Gotcha. If you would need any help with maintaining the project, feel free to ping me. I will be happy to help.

> we use barrel on the refinery tests, so yeah it's still supported. Can you open another issue with a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)?

Sure thing, thanks for the guidance. Filed an issue at #234.
