### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by TobiasDeBruijn** [rust-db/refinery#236]
Hi there,

Where is the source of `refinery` version `0.8.5`? The `master` branch's `refinery/Cargo.toml` is at `0.8.4`, however crates.io is at `0.8.5`.

Thanks!

**Comment by jxs** [comment]
Hi Tobias, how are you?

It seems when releasing `0.8.5` I forgot to submit the PR with the changes, doing it now would mean rebasing against the already introduced changes after and therefore have an inaccurate `0.8.5` commit. So what I did was release `0.8.6` and submit the PR with it. I'll probably also yank 0.8.5 as there isn't any reference in the code to it.

Meanwhile I **definitely** need to improve this process as this isn't the first time it happens, I'll probably automate the release/commit/tag process so it's done via github actions.

Thanks for your interest!

**Comment by TobiasDeBruijn** [comment]
Makes sense, no harm in yanking either I don' think. 

I could look into some CI to try and improve on the release process. Personally I use Git's tag feature for this: when a tag is created, a cargo release is made. Though of course that still requires verifying the version's specified in Cargo.toml's is correct, though I think adding a check that makes sure that at least `refinery/Cargo.toml` matches the tag name should be doable with some scripting.

Thanks!

**Comment by jxs** [comment]
>I could look into some CI to try and improve on the release process. Personally I use Git's tag feature for this: when a tag is created, a cargo release is made. Though of course that still requires verifying the version's specified in Cargo.toml's is correct, though I think adding a check that makes sure that at least refinery/Cargo.toml matches the tag name should be doable with some scripting.

yeah [I already use the tag system for github containers and releases](https://github.com/rust-db/refinery/blob/main/.github/workflows/releases.yml), so maybe it would make sense to also add the `cargo` publishing step there.  
The downsides are that if the pipeline breaks (like it just recently did) it's messy to fix it.  
We can try it and see how it goes, no need for the script that asserts the tag matches, that is a thing we can do manually:

1 - asserting the `Cargo.toml` and the tag match.
2 - assert the tag points to a `Release `x.x` version.

If I understand correctly you already have a pipeline like this set for one of your projects right?

Thanks!

**Comment by TobiasDeBruijn** [comment]
I've got something similar yes, though rather than publish to crates.io it publishes to GH releases, but crates.io should be easier, just requires figuring out the login.

I'll try to publish a PR today or tomorrow with the release CI.
