### ISSUE TITLE
Add support for ```rusqlite``` ```0.28.0``` 

### ISSUE THREAD

**Issue by hoangdt84** [rust-db/refinery#239]
Hi,

I found following line in ```refinery_core```'s [Cargo.toml](https://github.com/rust-db/refinery/tree/main/refinery_core/Cargo.toml): 
> rusqlite = { version = ">= 0.23, <= 0.27", optional = true }

Could you please let me know why we cannot use ```rusqlite``` version ```0.28.0```?

Thanks,

**Comment by jxs** [comment]
Hi,
we cannot use it cause it hasn't been added to the `Cargo.toml` you referred, do you want to submit a PR addressing this?
Thanks :)
