### ISSUE TITLE
Failed test `rusqlite::updates_to_last_working_if_not_grouped`

### ISSUE THREAD

**Issue by hoangdt84** [rust-db/refinery#240]
Hi,

I'm currently working on #239. After cloning and running test, I receive following report

> ---- rusqlite::updates_to_last_working_if_not_grouped stdout ----
> thread 'rusqlite::updates_to_last_working_if_not_grouped' panicked at 'assertion failed: `(left == right)`
>   left: `2959965718684201605`,
>  right: `15053093250517405828`', refinery\tests\rusqlite.rs:259:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Command: `cargo test --features rusqlite`
Environment 1: `rustc 1.63.0` / `Windows 11`
Environment 1: `rustc 1.63.0` / `Windows Subsystem for Linux (Rocky 9)`

What should I do to fix this test?

**Comment by jxs** [comment]
I take it this was fixed right? #241 doesn't fail

**Comment by hoangdt84** [comment]
This test fails with `rusqlite` `0.27.0` **and** `0.28.0`. So `rusqlite` is not the reason.

I guess it happens because of `rustc`. Mine is `1.63.0` but your CI is `1.56.0`.

**Comment by jxs** [comment]
ah right, we need to update it then thanks! Care to submit a PR addressing it?
Thanks :)

**Comment by jxs** [comment]
fixed with #259
