### ISSUE TITLE
Make `Migration::sql()` public

### ISSUE THREAD

**Issue by jess-sol** [rust-db/refinery#247]
Currently trying to implement [`sqlx::migrate::MigrationSource`][1] for refinery in order to use [`sqlx::test`][2]. As part of this, I need to translate `refinery_core::runner::Migration` to [`sqlx::migrate::Migration`][3]. It'd actually be a pretty simple mapping if refinery's `Migration::sqlx()` was public. As it stands I'm just manually reading the file as a hack, but it'd be much easier if there was a way to access a migration's sql.

[1]: https://docs.rs/sqlx/latest/sqlx/migrate/trait.MigrationSource.html
[2]: https://docs.rs/sqlx/latest/sqlx/attr.test.html
[3]: https://docs.rs/sqlx/latest/sqlx/migrate/struct.Migration.html

I could see making it a separate trait or something, if you wanted to make it difficult to access by default; but having some sort of escape hatch for these types of use-cases would be nice.

**Comment by jxs** [comment]
Hi, looking at it I cannot recall the reasoning for not making it public. So I'd say we can make it public? Do you want to submit a PR unsealing it?

**Comment by jess-sol** [comment]
Awesome, just created a PR

Thanks!

**Comment by jxs** [comment]
addressed with #249
