### ISSUE TITLE
Postgres backend doesn't report error positions

### ISSUE THREAD

**Issue by lf-** [rust-db/refinery#251]
I ran the following command with refinery-cli 0.8.6 from Nix, and it did not specify where the error was in the migration file. This is a usability issue.

To reproduce, create a migration file that contains errors and run it against Postgres.

```
» refinery migrate -e POSTGRES_CONNECTION_STRING -p db/migrations
schema history table is empty, going to apply all migrations
applying migration: U1664922413__initial_migration
Error: `error applying migration U1664922413__initial_migration`, `db error: ERROR: relation "workspaces" does not exist`

Caused by:
    0: db error: ERROR: relation "workspaces" does not exist
    1: ERROR: relation "workspaces" does not exist
```

**Comment by jxs** [comment]
Hi, `refinery` uses [`postgres`](https://docs.rs/postgres/0.19.4/postgres/) I'd say this is a problem with upstream, the `Error` is just bubbled.

**Comment by lf-** [comment]
This is actually a refinery problem in some sense because the postgres crate has the data but it's not output in the Display impl https://docs.rs/tokio-postgres/0.7.7/src/tokio_postgres/error/mod.rs.html#311

**Comment by jxs** [comment]
but if that's so, Postgres doesn't output it in the `Display` impl how come it's a `refinery` problem?

**Comment by lf-** [comment]
In principle it could be fixed on the refinery side by extracting the exact error, but really this should be fixed upstream. I'll look into a pr if i remember.
