### ISSUE TITLE
Funty 1.2.0 yanked

### ISSUE THREAD

**Issue by okkero** [rust-db/refinery#254]
I am unable to install refinery_cli now, since funty 1.2.0 has been yanked up stream. I don't know how easy that is to fix or work around in this crate, since funty is not a direct dependency, but I thought I'd file an issue anyway, since it messes with my CI pipelines.

**Comment by solidiquis** [comment]
Same

**Comment by TobiasDeBruijn** [comment]
For Funty pulled in by the `mysql` feature, this is solved in #257

**Comment by jxs** [comment]
Hi folks sorry for the delay, will cut a release today with #257
Thanks!

**Comment by jxs** [comment]
addressed with https://github.com/rust-db/refinery/pull/259 thanks!
