### ISSUE TITLE
rusqlite version bump?

### ISSUE THREAD

**Issue by netvl** [rust-db/refinery#26]
Currently refinery depends on rusqlite 0.18, while the latest version is 0.21. Because rusqlite links to a native library, it is not possible to have multiple versions of it in the same build. Consider upgrading to the latest version of rusqlite.

**Comment by jxs** [comment]
Hi
thanks for noticing! :+1: 
released 0.2.0-alpha.2 with rusqlite dependency bumped to 0.21
