### ISSUE TITLE
Custom schema history name

### ISSUE THREAD

**Issue by JenyaFTW** [rust-db/refinery#262]
By default, the table name for storing migration history is `refinery_schema_history`. Is there are a way to change this or possibly to change the schema (public by default) that the table is put in?

**Comment by jxs** [comment]
Hi! See https://github.com/rust-db/refinery/pull/207

**Comment by JenyaFTW** [comment]
What if I'm using refinery_cli?

**Comment by jxs** [comment]
that's not possible yet, would you like to submit a PR addressing that? Should be simple, adding a cli flag to activate the `Runner` option.

**Comment by JenyaFTW** [comment]
@jxs Sure. I'm not sure what the flag should be though? I was thinking `-t` for table name but that's already taken. Is a long flag `--table-name` okay?

**Comment by jxs** [comment]
yeah using a long name is ok 🙂

**Comment by JenyaFTW** [comment]
Opened PR #263 @jxs

**Comment by jxs** [comment]
Adressed with #263
