### ISSUE TITLE
Leading 0's in migration number

### ISSUE THREAD

**Issue by enricozb** [rust-db/refinery#284]
I want to have my migrations be in lexicographic order, so I tried something like this:
```
migrations/
  V000001__init.sql
  V000002__add-something.sql
  ...
```
However `refinery` doesn't seem to pick these up when I do
```rust
embedded::migrations::runner()
  .run_async(&mut client)
  .await
  .context("Failed to migrate")?;
```
If I change the names to `V1__init.sql` and `V2__add-something.sql` then they get picked up.

The regex [here](https://github.com/rust-db/refinery/blob/cf6e3d6fefd219c6f5ed630050e5a6e6696b4c89/refinery_core/src/runner.rs#L16) should pick up these files with leading zeros:
```rust
Regex::new(r"^([U|V])(\d+(?:\.\d+)?)__(\w+)").unwrap()
```
but it doesn't seem to.

Additionally, parsing an `i32` with leading zeros works:
```rust
fn main() {
  let a: i32 = "00001".parse().unwrap();
  println!("{:?}", a);
}
```

So I'm unsure of:
1. Why this doesn't already work
2. Are leading zeros intentionally not supported?

**Comment by jxs** [comment]
Hi, and thanks for your interest! Do you have  a MRE showing migrations with leading zeros not being picked up?
Thanks

**Comment by jxs** [comment]
closing this out of staleness, feel free to open it again if and when you have more details.
Thanks
