### ISSUE TITLE
Broken docker image 0.8.11

### ISSUE THREAD

**Issue by mariusgassen** [rust-db/refinery#288]
Since updating to version 0.8.11, the docker image cannot be run anymore.

```
> docker run -it --name refinery ghcr.io/rust-db/refinery:0.8.11
/usr/local/bin/refinery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/refinery)
/usr/local/bin/refinery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/bin/refinery)
/usr/local/bin/refinery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/refinery)
```

**Comment by jxs** [comment]
Hi, and thanks for reporting this! Yeah it's probably a mismatch in the `libc` of the builder container and the runner container, let me submit a PR with a fix and rebuild the containers

**Comment by jxs** [comment]
[CI is running](https://github.com/rust-db/refinery/actions/runs/6237956664) we just need for it to finish, after you remove the current `0.8.11`  and pull it again it should work.
Thanks!
