### ISSUE TITLE
Support mysql 24.0.0

### ISSUE THREAD

**Issue by raffaeleragni** [rust-db/refinery#291]
Mysql current driver version is 24, but this crate can't compile against it.

**Comment by jxs** [comment]
Hi, and thanks for your interest! Care to submit a PR addressing it? See https://github.com/rust-db/refinery/pull/257 for an example

**Comment by glueball** [comment]
Also mysql_async v0.33.

**Comment by glueball** [comment]
I've tried to contribute a PR both for mysql v24 and mysql_async v0.33. CI is green. As soon as the maintainers can approve it, Refinery should be good to go with those versions ;)
