### ISSUE TITLE
Support SurrealDB

### ISSUE THREAD

**Issue by TECHNOFAB11** [rust-db/refinery#294]
It would be awesome to be able to use this to migrate SurrealDB databases as well.
From quickly looking into the code it seems like it should be fairly easy to implement Migrate/AsyncMigrate for the SurrealDB client but the SQL for working with the table that contains the applied migrations is constant and SurrealDB probably does not understand that.
The migration files currently just support .sql and .rs, which should be fine (the only downside being Intellisense not knowing that the .sql file contains SurrealQL) but supporting .surql would be nice.

If anyone has an idea what the best way of handling the SQL consts is I can try and implement support for SurrealDB :)

**Comment by jxs** [comment]
replied on #295
