### ISSUE TITLE
Update broken Flyway documentation link

### ISSUE THREAD

**Issue by alilleybrinker** [rust-db/refinery#297]
In the project README there's a link to Flyway's documentation explaining how Refinery and Flyway share the same philosophy about rollback migrations. However, the link appears to be broken, and just goes to the main page of the Flyway documentation, which doesn't address migrations at all. I'm guessing Flyway rearchitected their docs, though I'm not sure what the new correct page would be for this.

**Comment by jxs** [comment]
Hi, and thanks! Submitted #299 299 to address it
