### ISSUE TITLE
serde properties of Config should be under a feature gate along with Toml serde impl

### ISSUE THREAD

**Issue by vasilakisfil** [rust-db/refinery#308]
Apparently [Config](https://docs.rs/refinery/latest/refinery/config/struct.Config.html) already allows you to config it programmatically. However, `refinery-core` (used by `refinery`) uses [serde](https://github.com/rust-db/refinery/blob/main/refinery_core/Cargo.toml#L24) by default to support serialization and deserialization of this type.

This is unnecessary if you don't use `refinery-cli` and configure it programmatically (using the `set_xxx` methods).

On top of that, `refinery` makes the assumption that Toml will be used to deserialize/serialize this type, as [toml](https://github.com/rust-db/refinery/blob/main/refinery_core/Cargo.toml#L27) dependency  is used as well in `refinery-core` by default. Again it's not always the case, this is more related with `refinery-cli`.

I suggest declaring both [toml](https://github.com/rust-db/refinery/blob/main/refinery_core/Cargo.toml#L27) and [serde](https://github.com/rust-db/refinery/blob/main/refinery_core/Cargo.toml#L24) dependencies as optional, under a feature flag. They can appear under the `default-features`, if they are used so often. It will also help not breaking anyone's code.

**Comment by jxs** [comment]
Hi, yeah makes sense, would you like to submit a PR addressing this?
Thanks!
