### ISSUE TITLE
Add support for rusqlite 0.31.0

### ISSUE THREAD

**Issue by rjkz808** [rust-db/refinery#316]
A new version of `rusqlite` was released 2 weeks ago (https://github.com/rusqlite/rusqlite/releases/tag/v0.31.0) but it can't be used with `refinery` due to the same problem as in #306.

**Comment by jxs** [comment]
Hi, and thanks for the interest! Care to submit a PR updating it? see https://github.com/rust-db/refinery/pull/300 for an example

**Comment by rjkz808** [comment]
Yes, sure - #317

**Comment by mkroman** [comment]
Any idea when this will make it into a release?

**Comment by jxs** [comment]
thanks for the ping @mkroman [released 0.8.13](https://github.com/rust-db/refinery/pull/322)
