### ISSUE TITLE
Expose features to select db drivers

### ISSUE THREAD

**Issue by onelson** [rust-db/refinery#33]
I was planning to try refinery_cli for some postgres work, but noticed the crate depends on libsqlite3 whether or not I want to use sqlite.

I didn't have it installed on my system at the time, so the build failed. I thought I'd mention it here as a feature request. Seems like others may have specific dbs in mind and will also want to pick and choose.

Thanks!

**Comment by jxs** [comment]
Hi, yeah it totally makes sense, I forgot to include the `bundle` feature for rusqlite on refinery_cli, and weirdly the CI containers don't complain, but you are right, i am going to allow refinery_cli install to pick the desired driver, and by default pick all 3 with rusqlite having sqlite bundled
thanks!

**Comment by jxs** [comment]
fixed it with #32. I am going to release 0.2 as soon as #30 lands, can you install from git for now?
thanks!

**Comment by onelson** [comment]
I uninstalled `libsqlite3-dev`, reinstalled from git with default features and it worked great. 

I also reinstalled with `--no-default-features --features postrgres` and had similar success. Thanks very much!
