### ISSUE TITLE
Build error with tiberius without serde

### ISSUE THREAD

**Issue by krojew** [rust-db/refinery#331]
When building `refinery-core` with `tiberius` feature but without `serde`, there a build error at config.rs:274:7:

```
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
struct Main {
    db_type: ConfigDbType,
    db_path: Option<PathBuf>,
    db_host: Option<String>,
    db_port: Option<String>,
    db_user: Option<String>,
    db_pass: Option<String>,
    db_name: Option<String>,
    #[cfg(feature = "tiberius-config")]
    #[serde(default)]
    trust_cert: bool,
}
```

`#[serde(default)]` is not guarded against not having `serde` feature, thus resulting in "cannot find attribute `serde` in this scope".

**Comment by jxs** [comment]
Hi, this is indeed a bug, but it shouldn't be reproducible as one shouldn't build `refinery-core`, specially with `tiberius-config` which is  a feature only used by `refinery-cli`, may I ask why are you doing it?

**Comment by krojew** [comment]
If I recall correctly, there was a case for it in https://github.com/krojew/springtime/tree/master/springtime-migrate-refinery, but can't remember exactly what.
