### ISSUE TITLE
Allow up/down migrations

### ISSUE THREAD

**Issue by Callum-A** [rust-db/refinery#338]
Allow migrations with an up (apply step) and a down (rollback step if needed).

**Comment by jxs** [comment]
Hi, this has been covered before, see https://github.com/rust-db/refinery/issues/121

**Comment by Callum-A** [comment]
> Hi, this has been covered before, see #121

Fair points, apologies for the duplicate!

**Comment by jxs** [comment]
no worries, and thanks for the interest!
