### ISSUE TITLE
Missing some functions in docs.rs

### ISSUE THREAD

**Issue by akhilles** [rust-db/refinery#39]
[`refinery::Runner`](https://docs.rs/refinery/0.2.0/refinery/struct.Runner.html) docs don't include the `Runner::run` and `Runner::run_async` functions.

I noticed that docs metadata was commented out in `Cargo.toml`:

```toml
# [package.metadata.docs.rs]
# features = ["postgres", "mysql", "sqlite", "extras"]
# no-default-features = true
```

was this intentional?

Also, the links for `embedded_migrations` and `include_migration_mods` are broken in https://docs.rs/refinery/0.2.0/refinery/index.html.

**Comment by jxs** [comment]
Hi, and thanks for your interest!
no, that was definitely not intentional :sweat_smile: yeah I forgot to uncomment docs metadata, and to fix the broken links.
want to submit a PR fixing it?
thanks
