### ISSUE TITLE
merge refinery_migrations on refinery crate?

### ISSUE THREAD

**Issue by jxs** [rust-db/refinery#41]
afair, when we started developing refinery, `refinery_cli` used functions from `refinery` that were not meant to be public, since `refinery_cli` also has to be an independent crate , we moved them to `refinery_migrations`.
We have since pub'ed `migrate_from_config`, so that reason doesn't seem to be legit anymore. 
from a quick glance at `refinery_cli`  it seems the only function that is still used without being doc'ed and oficially pub'ed is `find_migration_filenames`, maybe we can also make it pub and document it to be able to be used with `migrate_from_config`, and then merge `refinery_migrations` into `refinery`?

**Comment by jxs** [comment]
@akhilles wanna give it a go?

**Comment by akhilles** [comment]
sure

**Comment by akhilles** [comment]
@jxs I'd like to better understand the search logic for the `find_migrations_filenames` function. According to the existing documentation, this is how the [`embed_migrations!`](https://docs.rs/refinery/0.2.0/refinery/macro.embed_migrations.html) and [`include_migration_mods!`](https://docs.rs/refinery/0.2.0/refinery/macro.include_migration_mods.html) macros should look for migration files:

- `embed_migrations!`: If a location is provided as input, then search for migration files in that location. If not, search for migration files in the `crate_root/migrations` directory.
- `include_migration_mods!`: If a location is provided as input, then search for migration files in that location. If not, search for migration files in the `crate_root/src/migrations` directory.

This makes sense to me but I noticed that the `find_migrations_filenames` function doesn't strictly align with this. It recursively looks for migration files in _any_ subdirectory under the crate root which ends in "migrations". Should the docs be updated to reflect this?

I'd be more inclined to update `find_migrations_filenames` such that its behavior strictly aligns with the existing docs.

**Comment by jxs** [comment]
> This makes sense to me but I noticed that the find_migrations_filenames function doesn't strictly align with this. It recursively looks for migration files in any subdirectory under the crate root which ends in "migrations". Should the docs be updated to reflect this?

from what I am seeing, [find_migrations_filenames](https://github.com/rust-db/refinery/blob/master/refinery_migrations/src/utils.rs#L32) if a parent was not provided, starts searching recursively from the current dir, then if the parent was not provided, searches for a parent `migrations` dir exactly.
Your suggestion is to be the macros define the root location for starting the recursive search, rather than `find_migration_filenames` have the check of a migrations dir? 
I am not sure, but I think the reason I made `find_migration_filenames` behave like that was because at the time I could not get the crate root dir at compile time, when the macros were being evaluated can you confirm that it is possible? if so i am happy to have that update on `find_migrations_filenames` :+1:

**Comment by akhilles** [comment]
I believe it's possible with the `CARGO_MANIFEST_DIR` environment variable. Cargo provides this at compile time.

**Comment by jxs** [comment]
ok awesome!
