### ISSUE TITLE
Migration files are no longer detected when using the master branch

### ISSUE THREAD

**Issue by aloucks** [rust-db/refinery#49]
While investigating an [int conversion](https://github.com/rust-db/refinery/pull/48) issue when using CockroachDB, I noticed that migrations didn't work at all on the master branch:

    INFO  refinery_migrations::traits::r#async > no migrations to apply

I'll see this even after dropping all the tables, including the schema migrations table. 

This seems to be a regression from the version on crates.io. I didn't see a branch for the older version but was able to dig out the release commit for `0.2`. I applied the int conversion patch to confirm that the old version works as expected (and it does).

https://github.com/aloucks/refinery/tree/version-i64

**Comment by akhilles** [comment]
The `refinery_migrations` crate was merged into `refinery`. So, it's strange to see `refinery_migrations` in the logs.

How did you specify your dependencies in `Cargo.toml`?

**Comment by aloucks** [comment]
Sorry, the copy/paste was probably from the wrong position in my scrollback buffer. 

This is from your integer-to-int4 branch after wiping out the database:

```
 DEBUG tokio_postgres::simple_query > executing statement batch: BEGIN
 DEBUG tokio_postgres::simple_query > executing statement batch: CREATE TABLE IF NOT EXISTS refinery_schema_history( version INT4 PRIMARY KEY,name VARCHAR(255),applied_on VARCHAR(255),
             checksum VARCHAR(255));
 DEBUG tokio_postgres::simple_query > executing statement batch: COMMIT
 DEBUG tokio_postgres::simple_query > executing statement batch: BEGIN
 DEBUG tokio_postgres::prepare      > preparing query s1: SELECT version, name, applied_on, checksum FROM refinery_schema_history ORDER BY version ASC;
 DEBUG tokio_postgres::query        > executing statement s1 with parameters: []
 DEBUG tokio_postgres::simple_query > executing statement batch: COMMIT
 INFO  refinery::traits             > schema history table is empty, going to apply all migrations
 INFO  refinery::traits::r#async    > no migrations to apply

```

**Comment by jxs** [comment]
Hi @aloucks, hmm are you running the migrations using the `embed_migrations` or `include_migration_mods` with a custom location?

**Comment by aloucks** [comment]
I'm using `embed_migrations`

**Comment by jxs** [comment]
and are you using it giving a custom location as input?

**Comment by aloucks** [comment]
Yes, I'm giving it the path relative to the workspace root (which works in the crates.io version).

**Comment by akhilles** [comment]
Could you provide your directory structure (including where the migration files are) as well as the path you're using in the `embed_migrations!()` macro?

**Comment by akhilles** [comment]
Could you provide something like this:

```
.
├── Cargo.toml
├── migrations
│  ├── V1__initial.sql
│  └── V2__gateway_tables.sql
└── src
   └── main.rs
```

```rust
// main.rs
mod embedded {
    refinery::embed_migrations!("./migrations");
}
```

^ this is layout I'm using and it works as expected

**Comment by aloucks** [comment]
```
workspace/
- Cargo.toml
- project1/
-- Cargo.toml
- project2/
-- Cargo.toml
-- src/
--- lib.rs
-- etc/
--- migrations/
---- V001_initial.sql
```

`project2/src/lib.rs`:

```rust
refinery::embed_migrations!("project2/etc/migrations");
```

I also noticed that the macro is not using `include_str!`, which seems to prevent the compiler from picking up changes in the scripts. I have to clean the project or modify `lib.rs` in order to pick up changes in the migrations (at least on the crates.io version where it detects them).

**Comment by jxs** [comment]
can you confirm that calling `refinery::embed_migrations!("etc/migrations");` works?

**Comment by akhilles** [comment]
> I also noticed that the macro is not using include_str!, which seems to prevent the compiler from picking up changes in the scripts. I have to clean the project or modify lib.rs in order to pick up changes in the migrations (at least on the crates.io version where it detects them).

I've been meaning to make this change. This should probably be tracked in a different issue. My current workaround is I have a build script that prints out `cargo:rerun-if-changed=` statements.

**Comment by aloucks** [comment]
> can you confirm that calling `refinery::embed_migrations!("etc/migrations");` works?

It did not work. It also no longer complains if I put a path in there that I know is wrong.

I then tried to changing it to windows style path separators.. and it did work:

```
refinery::embed_migrations!("etc\\migrations");
```

It looks like the problem is that the path is being canonicalized prior to the concatenation.

**Comment by aloucks** [comment]
Although the fix in the PR I submitted resolves the issue with path concatenation, the behavior is still different from the current version (which assumes paths are relative to the workspace root or where cargo is run from). It might be a good idea to add a note in the change log about that.

With that said, the behavior is still different from the standard `include_str!` macro that uses paths relative to the file.

**Comment by akhilles** [comment]
The published version resolves paths relative to where `cargo` is executed. IMO, the updated behavior fits the description in the docs a bit better:
> If you want to specify another directory call `embed_migrations!` with it's location relative to the root level of your crate.

We should definitely include it in the changelog for 0.3.0.

I thought about using paths relative to the source file, but similar macros outside the standard library (like [`include_dir!`](https://docs.rs/include_dir/latest/include_dir/) and [`diesel_migrations::embed_migrations!`](https://docs.rs/diesel_migrations/latest/diesel_migrations/macro.embed_migrations.html)) use paths relative to crate root, so it seemed like the more standard approach. I'm fine with either approach though, @jxs wdyt?

Also, `embed_migrations!` should probably panic if an invalid path is provided or if no migration files are found.

**Comment by jxs** [comment]
yeah, I think what makes more sense is the path being relative to the crate root and that was what I intended with the initial version, let's address this change on the release of the `0.3` which I plan to do after including support for [`SQLx` ](https://crates.io/crates/sqlx)

> Also, embed_migrations! should probably panic if an invalid path is provided or if no migration files are found.

was this happening before #43 ? I don't recall right now

**Comment by akhilles** [comment]
@jxs before, it would panic if an invalid path is provided, but would not panic if no migration files are found. Does it make sense to panic under both circumstances?

**Comment by jxs** [comment]
hmm maybe panic it's too aggressive, but a warning/error would be nice, wdyt?

**Comment by JohnKinyanjui** [comment]
> Could you provide something like this:
> 
> ```
> .
> ├── Cargo.toml
> ├── migrations
> │  ├── V1__initial.sql
> │  └── V2__gateway_tables.sql
> └── src
>    └── main.rs
> ```
> 
> ```rust
> // main.rs
> mod embedded {
>     refinery::embed_migrations!("./migrations");
> }
> ```
> 
> ^ this is layout I'm using and it works as expected

after i added the double dashes "__" it worked i.e:
V1_init.sql - does not work
V1__init.sql - works like a charm
