### ISSUE TITLE
Ability to migrate to a specific version?

### ISSUE THREAD

**Issue by jsdw** [rust-db/refinery#60]
Hello, and thanks for this crate!

I was wondering whether it's on the roadmap to support running migrations up to a specific version, rather than all the way. If not, I'd be curious to know what your stance on the matter is (particularly because I am fairly inexperienced at the DB layer, so any insight is very welcome)!

**Comment by jxs** [comment]
Hi!, it is not on the road map, but is totally feasible, can you describe your use case?

**Comment by jsdw** [comment]
This is just something I've seen in eg Alembic. I suppose the main use case is to allow migrating to non-latest schema versions for the sake of testing migrations.
