### ISSUE TITLE
Use a stable hash algorithm for checksums

### ISSUE THREAD

**Issue by aloucks** [rust-db/refinery#62]
The [`DefaultHasher`](https://doc.rust-lang.org/std/collections/hash_map/struct.DefaultHasher.html) intentionally omits details of what algorithm is used:

> The internal algorithm is not specified, and so it and its hashes should not be relied upon over releases.

[`sha1`](https://docs.rs/sha-1/0.8.2/sha1/) is probably a better choice.

**Comment by jxs** [comment]
Hi, nice catch thanks!
yeah we should def use a stable hasher, thing is Rust core seems to be using `SipHasher13` so, to avoid breaking changes I would rather use [`rust-siphash`](https://github.com/jedisct1/rust-siphash) which seems to be using the same implementation as rust core. Want to give it a go?
