### ISSUE TITLE
Lack of ability to change logic of detection of earlier applied migrations

### ISSUE THREAD

**Issue by survived** [rust-db/refinery#68]
My project used to have self-written migration manager, now I'm trying to figure out if I can explain to refinery how my migration version control is organized. In other words, before `refinery` retrieves previously applied migration versions, I need to check if database uses old fashion version control and if it does, retrieve applied versions in old-fashion way and make `refinery` think that those migrations have been applied as if `refinery` had applied them by itself.

Diesel_migrations exposes [trait MigrationConnection](https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/trait.MigrationConnection.html) so I can simply wrap it and make it know if some migrations have been applied earlier. In contrast, refinery has Query trait (which is subset of MigrationConnection) but [hides it](https://github.com/rust-db/refinery/blob/0ea5a319a2276d16a160b8a44f07e275a805fba2/refinery/src/traits/sync.rs#L12).

I think idea of having MigrationConnection is good enough to reuse.

**Comment by jxs** [comment]
Hi, yeah that makes sense and can def be done, what kind of functions/values would  you like to be able to be called on a connection?

**Comment by survived** [comment]
Thanks for reply! I'd like be able to call method "mark migration as applied" that makes refinery believe that this migration have been actually applied as if refinery had applied it in regular way. 

"Retrieve all previously applied migration versions" and "retrieve latest applied migration version" are also should be introduced in this trait in my opinion, but them are not required to cover my case.
