### ISSUE TITLE
Tests in `refinery/` and `refinery_core/` are not run on circle_ci

### ISSUE THREAD

**Issue by zoechi** [rust-db/refinery#71]
See also https://github.com/rust-db/refinery/pull/70#issuecomment-599981122
Running tests in `refinery/` seem to be only configured for Travis, but according to badges on the README CI is done with CircleCI.

**Comment by jxs** [comment]
thanks! yeah I missed adding refinery_core tests to the ci step, and modifying the travis (windows) ones
