### ISSUE TITLE
How to enable MigrationType::Mod?

### ISSUE THREAD

**Issue by fundon** [rust-db/refinery#76]
https://github.com/rust-db/refinery/blob/2adb1b2489adf699f9dc8fe74319eac556bf656f/refinery_cli/src/migrate.rs#L36
https://github.com/rust-db/refinery/blob/master/refinery_core/src/util.rs#L10-L13

**Comment by jxs** [comment]
hi, to enable migrating by mod you should use the [`include_migration_mods`](https://docs.rs/refinery/0.2.1/refinery/macro.include_migration_mods.html)

**Comment by fundon** [comment]
Thanks, I try it.
