### ISSUE TITLE
no method named `run` found for struct `refinery::Runner` in the current scope

### ISSUE THREAD

**Issue by sbrl** [rust-db/refinery#77]
Hello,

I'm a Rust beginner, and I've tried to set this crate up to do migrations on my database. Unfortunately, I'm getting the following error:

```
error[E0599]: no method named `run` found for struct `refinery::Runner` in the current scope
  --> wopplebloxd/src/db/migrations.rs:22:40
   |
22 |         embedded::migrations::runner().run(&mut connection);
   |                                        ^^^ method not found in `refinery::Runner`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

For context, here's my `migrations.rs` file:

```rust
use super::definitions::{ Connection };
// use rusqlite::Connection;

mod embedded {
    use refinery::embed_migrations;
    
    embed_migrations!("wopplebloxd/migrations");
}

pub struct SqliteMigrator;

impl Default for SqliteMigrator {
    fn default() -> SqliteMigrator {
        SqliteMigrator {
            
        }
    }
}

impl SqliteMigrator {
    pub fn migrate(&self, connection : &mut Connection) {
        embedded::migrations::runner().run(&mut connection);
    }
}
```

....which references `definitions.rs`:

```rust
pub type Pool = r2d2::Pool<r2d2_sqlite::SqliteConnectionManager>;
pub type Connection = r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>;
```

I'm using r2d2 & r2d2-sqlite, as I'm building a web app with actix. If I don't do that, then I get errors because the plain-old `rusqlite::Connection` can't be shared across multiple threads (which are spawned automatically by actix).

I also have a `migrations` folder that contains a single `.sql` file called `V1__initial.sql`.

**Comment by jxs** [comment]
Hi, have you enabled the desired driver as a feature? eg `refinery = { version = "0.2", features = ["rusqlite"]}` ?
but you are right, you are not the first one to have this setback, i am going to update the doc

**Comment by sbrl** [comment]
Ah, that did the trick! Thanks @jxs. That makes me feel better - glad I'm not the only one haha

Does _refinery_ have an option to support r2d2_sqlite for connection pooling? I'm now getting this error:

```
]error[E0277]: the trait bound `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>: refinery_migrations::traits::sync::Query<std::vec::Vec<refinery_migrations::AppliedMigration>>` is not satisfied
  --> wopplebloxd/src/db/migrations.rs:23:44
   |
23 |         embedded::migrations::runner().run(&mut connection);
   |                                            ^^^^^^^^^^^^^^^ the trait `refinery_migrations::traits::sync::Query<std::vec::Vec<refinery_migrations::AppliedMigration>>` is not implemented for `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>`
   |
   = note: required because of the requirements on the impl of `refinery::Migrate` for `&mut r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `wopplebloxd`.

To learn more, run the command again with --verbose.
```

I'm having to use connection pooling here because I'm setting up a web server with actix, and I'm storing my db connection in my global state object, which is access by multiple threads I assume that actix is spawning.

**Comment by jxs** [comment]
can you open a separate issue with that feature request? I closed this one since it has been addressed

**Comment by sbrl** [comment]
Sure thing - opened #79 @jxs
