### ISSUE TITLE
Mismatch in name of config file when created by cli setup vs what cli migrate expects

### ISSUE THREAD

**Issue by mcobzarenco** [rust-db/refinery#80]
First, :100: for the project! 

The `refinery_cli` creates a `refinery.toml` config file when running `refinery setup` -- however, `refinery migrate` expects the file to be called `Refinery.toml` 

As a passing comment, in the cli [readme](https://github.com/rust-db/refinery/tree/master/refinery_cli), the examples use `refinery_cli`, but the executable seems to be called `refinery` when installing as suggested with `cargo install refinery_cli`.

**Comment by jxs** [comment]
> The refinery_cli creates a refinery.toml config file when running refinery setup -- however, refinery  migrate expects the file to be called Refinery.toml

yeah, that has been fixed in the master, both are now using `refinery.toml`: https://github.com/rust-db/refinery/blob/master/refinery_cli/src/cli.rs#L18 and https://github.com/rust-db/refinery/blob/master/refinery_cli/src/cli.rs#L18 

>As a passing comment, in the cli readme, the examples use refinery_cli, but the executable seems to be called refinery when installing as suggested with cargo install refinery_cli.

yeah you are right, want to submit a PR fixing it?
thanks!

**Comment by mcobzarenco** [comment]
> yeah, that has been fixed in the master, both are now using refinery.toml
:+1: looking forward to a release, but in the meantime I'll switch to installing from master, thanks!

> yeah you are right, want to submit a PR fixing it?
Sure thing! (#85)

**Comment by jxs** [comment]
> +1 looking forward to a release, but in the meantime I'll switch to installing from master, thanks!
yeah I plan too as soon as nightly is fixed and I have time to address other features
tanks
