### ISSUE TITLE
"ERROR: no database specified" when trying to create migrations table

### ISSUE THREAD

**Issue by mcobzarenco** [rust-db/refinery#81]
I am getting 
```
Error: `error asserting migrations table`, `db error: ERROR: no database specified`
```
when `refinery` tries to create the migrations table. What database should the `migrations` table be created in?

This is on linux, against CockroachDB (using postgres driver) -- I suspect the latter is more pedantic than postgres about specifying a database (but it's just a theory).

**Comment by jxs** [comment]
Hi, yeah I suspect it's the sql you are feeding the cockroachdb. the query in question is [this](https://github.com/rust-db/refinery/blob/master/refinery_core/src/traits/mod.rs#L78) can you try running that query against your db and see if it works?

**Comment by mcobzarenco** [comment]
Thanks for the reply -- running the query directly in cockroachdb fails with "no database specified"
```
> CREATE TABLE refinery_schema_history(
              version INT4 PRIMARY KEY,
              name VARCHAR(255),
              applied_on VARCHAR(255),
              checksum VARCHAR(255))

no database specified
```

My hypothesis is that `postgres` by default connects to a `postgres` database if none specified, whereas cockroach doesn't have a default.

Is it expected behaviour that the `refinery_schema_history` table gets created in the default database, irrespective of the configuration file?

**Comment by jxs** [comment]
> Is it expected behaviour that the refinery_schema_history table gets created in the default database, irrespective of the refinery.toml configuration file?

yeah, there is no logic to handle the database where refinery runs the queries, it just picks the default

**Comment by jxs** [comment]
i am going to close this one, as it's probably a problem with your cockroach db setup
