### ISSUE TITLE
Building under stable-x86_64-pc-windows-gnu fails

### ISSUE THREAD

**Issue by almetica** [rust-db/refinery#84]
Hi,

Currently refinery seems to fail to build under ```stable-x86_64-pc-windows-gnu``` and ```nightly-x86_64-pc-windows-gnu```.

```stable-x86_64-pc-windows-msvc``` on the other hand builds refinery fine.

Error message:
```bash
   Compiling refinery v0.2.1
error: could not compile `refinery`.

Caused by:
  process didn't exit successfully: `rustc 
--crate-name refinery 
--edition=2018 'C:\Users\almetica\.cargo\registry\src\github.com-1ecc6299db9ec823\refinery-0.2.1\src\lib.rs' 
--error-format=json 
--json=diagnostic-rendered-ansi,artifacts 
--crate-type lib 
--emit=dep-info,metadata,link -C debuginfo=2 
--cfg 'feature="default"' 
--cfg 'feature="postgres"' -C metadata=b4b0923c9635f1a1 -C extra-filename=-b4b0923c9635f1a1 
--out-dir 'C:\Users\almetica\Documents\Development\almetica\almetica\target\debug\deps' -L 'dependency=C:\Users\almetica\Documents\Development\almetica\almetica\target\debug\deps' 
--extern 'barrel=C:\Users\almetica\Documents\Development\almetica\almetica\target\debug\deps\libbarrel-c14e7acdbe063085.rmeta' 
--extern 'refinery_macros=C:\Users\almetica\Documents\Development\almetica\almetica\target\debug\deps\refinery_macros-fdbe15d768c175f7.dll' 
--extern 'refinery_migrations=C:\Users\almetica\Documents\Development\almetica\almetica\target\debug\deps\librefinery_migrations-ff4312ab516cca44.rmeta' 
--cap-lints allow -C target-cpu=native -L 'native=C:\Users\almetica\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'` 
(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Maybe https://github.com/rust-lang/rust/issues/33434 is related? 

Edit: ```--release``` works fine. So only debug build is affected. I will try to pinpoint the exact cause further.

**Comment by almetica** [comment]
Switching the debug build to optimization level 1 fixes the issue. I will try to reproduce this problem on another windows machine and if I can reproduce it, I will try to make a minimal example and report it upstream.

**Comment by almetica** [comment]
I can reproduce this bug only with my project and only on Windows 10, stable-gnu and Ryzen CPUs. As soon as I switch to a Windows 2019 server setup with Intel CPUs the problem disapears.

This is an odd one. I will close this issue and will report his bug once I successfully isolated the root cause of this bug.

**Comment by jxs** [comment]
thanks!
