### ISSUE TITLE
refinery-migrations 0.2.3 is a breaking change

### ISSUE THREAD

**Issue by vivianhellyer** [rust-db/refinery#93]
`refinery 0.2.1` depends on `refinery-migrations ^0.2.2`. `refinery-migrations 0.2.2` depends on `rusqlite ^0.21`, which depends on `libsqlite3-sys ^0.17`. `refinery-migrations 0.2.3` upgraded from `rusqlite ^0.21` to `rusqlite ^0.23`, which also upgraded `libsqlite-3sys` to `^0.18`.

The `refinery-migrations` update breaks builds for people who use other crates which currently depend on a different version of `libsqlite3-sys`, like current `sqlx-core` using `^0.17`. The `rusqlite` upgrade should've been done in a new major version (`0.3`) of `refinery-migrations` and `refinery`.

**Comment by jxs** [comment]
Hi, thanks for reporting! 
Yeah that was not supposed to happen, I have since yanked `refinery-migrations 0.2.3` and hope to have solved the issue
